language: php
php:
  - 5.5
  - 5.6

before_script:
  # Set up Composer
  - composer self-update || true
  - composer config http-basic.repo.magento.com $magento2-repos-username $magento2-repos-password
  - composer install --prefer-dist
  
script:
  - ./vendor/bin/phpunit -c phpunit.xml.dist